export type Level = "Iniciante" | "Intermediário" | "Todos";

export type Lesson = {
  id: string;
  title: string;
  level: Level;
  duration: string;
  tag?: string;
  hook: string;
  teach: string[];
  example?: string;
  task: string;
  closing: string;
};

export type Module = {
  code: string;
  title: string;
  goal: string;
  lessons: Lesson[];
};

export const PILLARS: { n: string; title: string; subtitle: string; body: string; science: string }[] = [
  {
    n: "01",
    title: "Mentalidade & Crenças",
    subtitle: "o destravamento",
    body: "Vem primeiro, não por último. Remove o medo, a vergonha e os mitos que travam o aluno antes de qualquer técnica.",
    science: "Filtro afetivo (Krashen): ansiedade e baixa motivação literalmente bloqueiam a aquisição.",
  },
  {
    n: "02",
    title: "Imersão / Input",
    subtitle: "o motor",
    body: "Consumir conteúdo que o aluno já ama (YouTube, audiolivros, leitura) com legenda/tradução. É onde ele passa a maior parte do tempo diário.",
    science: "Input compreensível (Krashen): input que você quase entende, um pouco acima do seu nível (i+1).",
  },
  {
    n: "03",
    title: "Conexão / Output",
    subtitle: "o acelerador",
    body: "Transformar entendimento passivo em fala ativa. Parceiro de intercâmbio real + prática de conversa na comunidade.",
    science: "Hipótese do output (Swain): produzir a língua com humanos reais consolida o aprendizado.",
  },
  {
    n: "04",
    title: "Fundamentos",
    subtitle: "os 25%",
    body: "A gramática e as regras que realmente destravam — ensinadas só o suficiente para o aluno não empacar. Call ao vivo semanal vive aqui.",
    science: "Gramática sob demanda: ensinar a regra quando ela resolve um problema concreto de comunicação.",
  },
];

export const JOURNEY: Module[] = [
  {
    code: "M1",
    title: "Mentalidade & Quebra de Crenças",
    goal: "Destravar a cabeça antes de qualquer técnica. Para iniciante e para quem empacou.",
    lessons: [
      {
        id: "m1l1",
        title: "A verdade sobre como adultos aprendem inglês",
        level: "Todos",
        duration: "8–10 min",
        hook: "Se você 'estudou inglês a vida toda' e ainda não fala, o problema não é você — é o método que te venderam. Nesta aula eu vou te mostrar como adultos REALMENTE aprendem um idioma.",
        teach: [
          "Diga que existe uma diferença entre APRENDER sobre o inglês (decorar regras) e ADQUIRIR inglês (entender e usar). A escola foca no primeiro; fluência vem do segundo.",
          "Explique a ideia central de Stephen Krashen: a gente adquire um idioma quando recebe muita mensagem que CONSEGUE entender — não quando decora gramática.",
          "Quebre o mito da criança: adultos aprendem mais rápido que crianças nos primeiros meses. O que crianças têm a mais é TEMPO de exposição e ZERO medo de errar — e os dois dá pra copiar.",
          "Apresente a lógica do método: 75% imersão + mentalidade, 25% gramática. Ao contrário da escola, que faz o oposto.",
        ],
        example: "Conte a história dos dois imigrantes: um vive nos EUA há 10 anos e mal fala inglês; o outro chegou já falando. A diferença nunca foi o país — foi exposição com sentido + uso real + ausência de medo.",
        task: "Escreva em uma frase: 'Eu não falo inglês ainda porque sempre me ensinaram a ___'. Poste na comunidade.",
        closing: "Você não é ruim de idiomas. Você só nunca usou o método certo. Isso muda a partir de hoje.",
      },
      {
        id: "m1l2",
        title: "Por que a escola tradicional falhou com você",
        level: "Todos",
        duration: "7–9 min",
        hook: "Você não desistiu do inglês. O método é que te abandonou primeiro. Deixa eu te mostrar exatamente onde a escola erra.",
        teach: [
          "Erro 1: ensinam gramática isolada, fora de qualquer contexto que importe pra você. Você decora 'present perfect' mas não consegue pedir um café.",
          "Erro 2: input artificial e chato (diálogos de livro didático) em vez de conteúdo que você de fato gosta.",
          "Erro 3: zero prática de fala real — no máximo repetir frase com o professor. Nunca uma conversa de verdade.",
          "Erro 4: ritmo de turma, não seu. Você avança quando a turma avança, não quando VOCÊ está pronto.",
          "Conclua: nada disso é culpa sua. E o método LatinusPro vira cada um desses erros do avesso.",
        ],
        task: "Liste os 3 motivos que mais te fizeram desistir antes. Vamos atacar cada um deles na comunidade.",
        closing: "A escola te ensinou a passar na prova. Aqui você vai aprender a conversar. São coisas diferentes.",
      },
      {
        id: "m1l3",
        title: "As 6 crenças que te travam",
        level: "Todos",
        duration: "12–15 min",
        hook: "Existe uma coisa que trava mais gente do que gramática: as histórias que você conta pra si mesmo. Vamos destruir as 6 principais.",
        teach: [
          "Apresente as 6 crenças (veja a aba 'Quebra de Crenças' para o roteiro detalhado de cada uma).",
          "Para cada crença, siga sempre a estrutura: Mito → Realidade → Ação concreta.",
          "Reforce a mais importante: 'preciso morar fora'. Mostre que é input + output + motivação, não geografia.",
          "Termine conectando com o filtro afetivo: o medo de errar é o maior bloqueio — e a comunidade existe pra reduzir esse medo.",
        ],
        task: "Escolha a crença que MAIS pesa em você e execute a ação correspondente hoje. Conte na comunidade qual foi.",
        closing: "Crença vira comportamento. Mude a história e o resto do método finalmente funciona.",
      },
      {
        id: "m1l4",
        title: "Definindo sua meta de 90 dias",
        level: "Todos",
        duration: "8–10 min",
        hook: "Sem um alvo claro, qualquer estudo vira ansiedade. Hoje você define uma meta que dá pra alcançar em 90 dias — e que você vai sentir.",
        teach: [
          "Explique por que 90 dias: tempo suficiente pra ver resultado real, curto o bastante pra manter foco.",
          "Defina a meta padrão da comunidade: 'ter minha primeira conversa real em inglês de 10 minutos com um parceiro'.",
          "Mostre como tornar a meta mensurável: vocabulário (ex.: +500 palavras), minutos de imersão por dia, nº de conversas.",
          "Ensine a quebrar em marcos semanais (semana 1: sistema montado; semana 4: primeiro áudio; semana 8: primeira conversa).",
        ],
        task: "Escreva sua meta de 90 dias no formato: 'Em 90 dias eu vou ___, medido por ___'. Fixe no seu perfil.",
        closing: "Você não precisa de fluência em 90 dias. Precisa de PROVA de que está funcionando. É isso que a meta entrega.",
      },
      {
        id: "m1l5",
        title: "Montando uma rotina diária que você sustenta",
        level: "Todos",
        duration: "9–11 min",
        hook: "A rotina que você não sustenta é pior do que rotina nenhuma. Vamos montar uma que sobrevive até nos dias ruins.",
        teach: [
          "Princípio: imersão SUBSTITUI consumo que você já faz, não soma horas novas. Troque o idioma do que você já assiste.",
          "Defina um mínimo inegociável pequeno (ex.: 15 min/dia). Pequeno demais pra falhar.",
          "Ancore o hábito a algo que já existe (café da manhã, trânsito, academia) — 'depois de X, eu faço imersão'.",
          "Separe dias bons (imersão + vocabulário + fala) de dias ruins (só o mínimo). O importante é não zerar o streak.",
        ],
        task: "Defina seu mínimo inegociável e a âncora dele. Poste: 'Todo dia, depois de ___, eu faço ___ minutos.'",
        closing: "Constância vence intensidade. 15 minutos por dia derrotam 3 horas no domingo, sempre.",
      },
    ],
  },
  {
    code: "M2",
    title: "O Método LatinusPro",
    goal: "Entender o sistema único que serve quem começa do zero E quem travou.",
    lessons: [
      {
        id: "m2l1",
        title: "Os 4 pilares em 10 minutos",
        level: "Todos",
        duration: "10 min",
        hook: "Todo o método cabe em 4 pilares. Entenda isso e você nunca mais vai se perder no que fazer a seguir.",
        teach: [
          "Pilar 1 — Mentalidade: remove o medo e as crenças que travam (já vimos no M1).",
          "Pilar 2 — Imersão/Input: o motor. A maior parte do seu tempo é consumir conteúdo que você ama, entendendo.",
          "Pilar 3 — Conexão/Output: o acelerador. Falar de verdade, com gente de verdade.",
          "Pilar 4 — Fundamentos: os 25% de gramática que destravam, sob demanda.",
          "Mostre que recompensa (streaks, vocabulário, marcos) é a camada que conecta tudo e te mantém voltando.",
        ],
        task: "Em uma frase, explique o método para um amigo como se ele tivesse 12 anos. Poste sua explicação.",
        closing: "Se você lembrar só dos 4 pilares, já sabe mais sobre aprender inglês do que 90% das escolas.",
      },
      {
        id: "m2l2",
        title: "Input compreensível: a ideia central",
        level: "Todos",
        duration: "9–11 min",
        hook: "Existe uma única ideia que, se você entender, muda tudo. Chama-se input compreensível. Vou te explicar em linguagem de gente.",
        teach: [
          "Defina: você adquire inglês quando recebe muita mensagem que você QUASE entende — nem fácil demais, nem difícil demais.",
          "Apresente o conceito do 'i+1': conteúdo um degrau acima do seu nível atual.",
          "Explique por que tradução/legenda ajuda: ela transforma input incompreensível em compreensível enquanto você ainda não tem vocabulário.",
          "Deixe claro: entender NÃO é traduzir cada palavra. É pegar a mensagem. Tolerar não entender 100% é parte do jogo.",
        ],
        example: "Compare com um bebê: ninguém explica gramática pra ele. Ele recebe MESES de input que faz sentido pelo contexto. Você vai fazer o mesmo, só que mais rápido porque já é adulto.",
        task: "Assista 5 minutos de um vídeo em inglês e anote: entendi a MENSAGEM geral? (não precisa entender toda palavra).",
        closing: "Pare de tentar entender cada palavra. Persiga a mensagem. A fluência mora aí.",
      },
      {
        id: "m2l3",
        title: "O ciclo: Input → Vocabulário → Output → repetir",
        level: "Todos",
        duration: "8–10 min",
        hook: "O método não é uma lista de tarefas soltas. É um ciclo que se retroalimenta. Deixa eu te mostrar a roda.",
        teach: [
          "Passo 1 — Input: você consome conteúdo que ama e entende.",
          "Passo 2 — Vocabulário: você minera as palavras novas desse conteúdo e fixa com repetição espaçada.",
          "Passo 3 — Output: você usa essas palavras falando (sozinho, gravando, ou com parceiro).",
          "Passo 4 — Repetir: cada volta o conteúdo fica mais fácil, então você sobe o nível do input.",
          "Mostre que o erro comum é pular o output — é por isso que o intermediário entende tudo mas não fala.",
        ],
        task: "Faça uma mini-volta hoje: 10 min de input → minere 5 palavras → fale 1 frase usando uma delas em voz alta.",
        closing: "Não é estudar mais. É girar essa roda todo dia. A roda é que faz a fluência.",
      },
      {
        id: "m2l4",
        title: "Diagnóstico: descubra seu ponto de partida",
        level: "Todos",
        duration: "7–9 min",
        hook: "Todo mundo aqui segue o MESMO caminho. A única coisa que muda é onde você começa o nível do conteúdo. Vamos descobrir o seu.",
        teach: [
          "Reforce: não existe trilha separada. O método é o mesmo pra todos; só o nível do material muda.",
          "Dê o autodiagnóstico simples: assista 2 min de conteúdo nativo (ex.: um podcast). Entendeu a ideia geral? → Intermediário. Travou nas primeiras frases? → Iniciante.",
          "Explique onde isso se aplica: na biblioteca de imersão (M3) e na biblioteca de gramática (M7) — você pega o material do seu nível.",
          "Tranquilize: o nível é só um ponto de partida; ele sobe sozinho conforme você gira o ciclo.",
        ],
        task: "Faça o teste de 2 minutos e marque seu ponto de partida (Iniciante ou Intermediário) no seu perfil.",
        closing: "Saber onde você começa evita dois erros mortais: o tédio do fácil demais e a frustração do difícil demais.",
      },
    ],
  },
  {
    code: "M3",
    title: "Sistema de Imersão (Input)",
    goal: "Tornar a imersão diária um hábito gostoso. A técnica é a mesma; só o nível do conteúdo muda.",
    lessons: [
      {
        id: "m3l1",
        title: "Como escolher conteúdo que você AMA",
        level: "Todos",
        duration: "8–10 min",
        hook: "O segredo número 1 da imersão não é o melhor material. É o material que você não consegue parar de assistir.",
        teach: [
          "Regra de ouro: escolha conteúdo sobre temas que você JÁ ama em português (futebol, games, maquiagem, negócios, séries).",
          "Por que funciona: prazer mantém o hábito, e contexto familiar torna o input compreensível mesmo com vocabulário menor.",
          "Dê os formatos: YouTube, podcasts, séries, audiolivros, canais de nicho.",
          "Alerta: largue o que é chato sem culpa. Material chato é a causa nº 1 de desistência.",
        ],
        task: "Liste 3 temas que você ama e encontre 1 canal/podcast em inglês para cada. Poste seus 3 achados.",
        closing: "Se a imersão parece estudo, você escolheu o conteúdo errado. Tem que parecer lazer.",
      },
      {
        id: "m3l2",
        title: "Configurar legenda dupla e tradução ao vivo",
        level: "Todos",
        duration: "10–12 min",
        hook: "Vou te mostrar a configuração exata que transforma qualquer vídeo do YouTube ou Netflix numa aula de inglês sob medida.",
        teach: [
          "Mostre na tela como instalar e usar a extensão de legenda dupla (ex.: Language Reactor) no navegador.",
          "Explique legenda dupla: inglês em cima, português embaixo — pra você conectar som, texto e significado.",
          "Ensine a progressão: comece com as duas legendas → depois só inglês → depois sem legenda.",
          "Mostre como clicar numa palavra pra ver a tradução e salvá-la pro vocabulário.",
          "Importante: não dependa só de uma ferramenta. Ensine alternativas (Anki, planilha) caso a extensão mude.",
        ],
        task: "Configure a legenda dupla em 1 vídeo e assista 5 minutos com ela. Tire um print e poste.",
        closing: "Essa configuração é a sua sala de aula particular — de graça, com o conteúdo que você ama.",
      },
      {
        id: "m3l3",
        title: "Biblioteca de conteúdo — nível Iniciante",
        level: "Iniciante",
        duration: "8–10 min",
        hook: "Se você ainda trava nas primeiras frases, NÃO comece pela série da Netflix. Comece por aqui — conteúdo feito pra ser entendido.",
        teach: [
          "Explique conteúdo graduado: vídeos e podcasts feitos pra aprendizes, com fala mais lenta e clara.",
          "Indique categorias: canais de 'comprehensible input for beginners', podcasts de inglês lento, vídeos infantis bem produzidos.",
          "Ensine a usar muita legenda no começo, sem culpa.",
          "Mostre o sinal de avanço: quando entender ~80% sem esforço, suba pro próximo nível.",
        ],
        task: "Escolha 1 fonte de conteúdo graduado da biblioteca e assista 10 minutos hoje.",
        closing: "Começar fácil não é fraqueza — é estratégia. Entender 80% é o que mantém você voltando.",
      },
      {
        id: "m3l4",
        title: "Biblioteca de conteúdo — nível Intermediário",
        level: "Intermediário",
        duration: "8–10 min",
        hook: "Você já entende o básico mas travou? O problema é que você nunca migrou pro conteúdo nativo real. Hora de subir o nível.",
        teach: [
          "Explique conteúdo nativo: feito por nativos pra nativos (podcasts reais, YouTubers, séries, audiolivros).",
          "Ensine a usar legenda só como apoio, reduzindo aos poucos.",
          "Aborde o desconforto: você vai entender menos no começo — isso é o 'i+1' funcionando, não fracasso.",
          "Mostre como minerar gírias, phrasal verbs e expressões idiomáticas do conteúdo nativo.",
        ],
        task: "Escolha 1 conteúdo nativo sobre um tema que você ama e assista 10 minutos reduzindo a legenda.",
        closing: "O intermediário não destrava com mais gramática. Destrava com conteúdo real e um pouco de desconforto.",
      },
      {
        id: "m3l5",
        title: "Audiolivros: ouvir e ler o texto ao mesmo tempo",
        level: "Todos",
        duration: "9–11 min",
        hook: "Existe uma técnica que junta leitura e escuta no mesmo exercício e acelera tudo: ouvir o audiolivro lendo o texto junto.",
        teach: [
          "Explique a sinergia: ouvir + ler ao mesmo tempo conecta o SOM da palavra à FORMA escrita.",
          "Recomende começar por livros que você já leu/ama em português (contexto conhecido = input compreensível).",
          "Ensine o fluxo: 1ª passada ouvindo e lendo; depois só ouvindo; depois só lendo.",
          "Indique onde achar (apps de audiolivro + e-book correspondente).",
        ],
        task: "Escolha um livro que você já conhece, pegue o áudio + texto e faça 1 capítulo ouvindo e lendo junto.",
        closing: "Ouvir lendo é como ter legenda na vida real. É um dos atalhos mais subestimados que existe.",
      },
      {
        id: "m3l6",
        title: "Shadowing: repetir junto com o áudio",
        level: "Todos",
        duration: "8–10 min",
        hook: "Quer melhorar pronúncia e ritmo sem aula de fonética? A técnica chama shadowing e é simples (mas poderosa).",
        teach: [
          "Defina shadowing: ouvir uma frase e repetir imediatamente, imitando ritmo, entonação e velocidade.",
          "Explique por que funciona: treina sua boca e seu ouvido ao mesmo tempo, copiando nativos.",
          "Dê o passo a passo: escolha um trecho curto → ouça → repita por cima → grave-se → compare.",
          "Dica: foque em IMITAR a melodia, não em entender cada palavra.",
        ],
        task: "Escolha 1 minuto de áudio e faça shadowing dele 3 vezes. Grave a última e ouça.",
        closing: "Você não precisa de aula de pronúncia. Precisa imitar gente de verdade, todo dia, um pouquinho.",
      },
      {
        id: "m3l7",
        title: "Sua meta diária de input",
        level: "Todos",
        duration: "6–8 min",
        hook: "Quanto de imersão por dia? Vou te dar um número realista que cabe na sua vida e ainda gera resultado.",
        teach: [
          "Dê a meta mínima: 15–20 min/dia de input compreensível. Ideal: 30–60 min se couber.",
          "Reforce: substitua, não some. Troque parte do consumo em português por inglês.",
          "Mostre como registrar no log de imersão da comunidade (alimenta o streak e a gamificação).",
          "Explique o efeito composto: 30 min/dia = ~180 horas/ano de exposição. É transformador.",
        ],
        task: "Defina sua meta diária de input e registre sua primeira sessão no log da comunidade hoje.",
        closing: "Não existe 'sem tempo'. Existe trocar o idioma do tempo que você já gasta.",
      },
    ],
  },
  {
    code: "M4",
    title: "Sistema de Vocabulário",
    goal: "Crescer o vocabulário de forma medível e recompensadora — o seu anti-Duolingo.",
    lessons: [
      {
        id: "m4l1",
        title: "Repetição espaçada explicada",
        level: "Todos",
        duration: "8–10 min",
        hook: "Você esquece o que aprende não porque tem memória ruim, mas porque revisa na hora errada. A repetição espaçada resolve isso.",
        teach: [
          "Explique a curva do esquecimento: a gente esquece rápido se não revisa.",
          "Defina repetição espaçada: revisar uma palavra em intervalos crescentes (1 dia, 3 dias, 1 semana, 1 mês).",
          "Mostre que o sistema mostra a palavra bem na hora em que você está prestes a esquecer — máxima eficiência.",
          "Conecte com vocabulário: é assim que você fixa as palavras mineradas da sua imersão.",
        ],
        task: "Escolha 5 palavras que você viu hoje e crie um flashcard de cada (vamos configurar a ferramenta na próxima aula).",
        closing: "Memória não é dom, é cronograma. Revise na hora certa e o vocabulário gruda.",
      },
      {
        id: "m4l2",
        title: "Montando seus flashcards",
        level: "Todos",
        duration: "10–12 min",
        hook: "Vou te mostrar como montar seu sistema de flashcards do zero — e te dar 3 opções pra você escolher a sua.",
        teach: [
          "Mostre as 3 opções: Language Reactor (salva direto do vídeo), Anki (poderoso e grátis), planilha LatinusPro (simples).",
          "Ensine o que vai no cartão: frente = palavra/frase em inglês no contexto; verso = significado + exemplo.",
          "Regra de ouro: salve a palavra DENTRO de uma frase real, nunca solta.",
          "Mostre na tela a criação de um cartão em cada ferramenta.",
        ],
        task: "Escolha SUA ferramenta e crie seus 5 primeiros cartões com frases reais. Poste qual ferramenta escolheu.",
        closing: "Não importa a ferramenta. Importa ter UMA e usar todo dia. Escolha e comece.",
      },
      {
        id: "m4l3",
        title: "Minerar palavras do conteúdo que você consome",
        level: "Todos",
        duration: "7–9 min",
        hook: "Pare de estudar listas de palavras aleatórias. As melhores palavras pra você estão no conteúdo que você já ama.",
        teach: [
          "Defina mineração: extrair as palavras/expressões novas do que você assiste e ler.",
          "Critério de seleção: salve só o que é útil e recorrente pra você — não tudo que não conhece.",
          "Mostre o fluxo: assistiu → marcou a palavra → salvou no flashcard com a frase → revisou depois.",
          "Limite saudável: 5–10 palavras novas por sessão pra não sobrecarregar.",
        ],
        task: "Na sua próxima imersão, minere 8 palavras e transforme em flashcards com a frase de origem.",
        closing: "Vocabulário relevante é o que aparece na SUA vida. Minere do que você ama e ele nunca some.",
      },
      {
        id: "m4l4",
        title: "Quantas palavras por dia (e por que menos é mais)",
        level: "Todos",
        duration: "6–8 min",
        hook: "Mais palavras por dia parece melhor, mas é a receita pra desistir. Vou te dar o número que realmente funciona.",
        teach: [
          "Dê o número: 5–10 palavras NOVAS por dia é sustentável e poderoso.",
          "Faça a conta: 7 palavras/dia = ~2.500 palavras/ano — vocabulário de conversação fluente.",
          "Explique por que pouco é melhor: você sustenta o hábito e a revisão não vira uma montanha.",
          "Reforce: o crescimento vem da CONSISTÊNCIA das revisões, não do volume diário.",
        ],
        task: "Defina sua meta diária de palavras novas (sugestão: 7) e ajuste sua ferramenta para esse limite.",
        closing: "7 palavras por dia parece pouco. Em um ano são milhares. É assim que se constrói fluência.",
      },
      {
        id: "m4l5",
        title: "Marcos de vocabulário: 1.000 / 2.000 / 5.000 palavras",
        level: "Todos",
        duration: "7–9 min",
        hook: "Aprender idioma sem ver progresso é desmotivante. Por isso a gente transforma vocabulário em placar — e celebra cada marco.",
        teach: [
          "Dê referências: ~1.000 palavras = conversa básica; ~2.000–3.000 = conversação confortável; ~5.000 = fluência ampla.",
          "Explique como acompanhar o número total na ferramenta e no seu perfil.",
          "Conecte com a comunidade: cada marco vira uma vitória pública celebrada por todos.",
          "Mostre o efeito psicológico: ver o número subir é o reforço positivo que substitui a 'gamificação' do Duolingo.",
        ],
        task: "Registre seu total atual de palavras e defina o próximo marco. Avise a comunidade quando bater.",
        closing: "O que é medido, melhora. Transforme seu vocabulário em número e veja a motivação cuidar de si mesma.",
      },
    ],
  },
  {
    code: "M5",
    title: "Destravar a Fala (Output)",
    goal: "Começar a falar antes de se sentir 'pronto'. O ponto onde o intermediário mais empaca.",
    lessons: [
      {
        id: "m5l1",
        title: "Por que você entende mas não consegue falar",
        level: "Todos",
        duration: "8–10 min",
        hook: "Você entende filme, música, podcast… mas na hora de falar trava. Isso tem explicação — e solução.",
        teach: [
          "Explique a diferença entre habilidade passiva (entender) e ativa (falar). Uma não vira a outra sozinha.",
          "Mostre a causa: você treinou só input. Falar é um músculo separado que precisa de prática própria.",
          "Tranquilize: travar não é falta de conhecimento, é falta de prática de produção + excesso de medo.",
          "Apresente a virada do método: começar a produzir output AGORA, mesmo imperfeito.",
        ],
        task: "Responda: o que você sente no corpo na hora de falar inglês? Nomear o medo é o primeiro passo pra vencê-lo.",
        closing: "Entender é a metade fácil. Falar é uma habilidade própria — e a partir de agora a gente treina ela.",
      },
      {
        id: "m5l2",
        title: "Falar sozinho e começar a pensar em inglês",
        level: "Todos",
        duration: "8–10 min",
        hook: "Você não precisa de outra pessoa pra começar a falar hoje. Vou te ensinar a treinar a fala sozinho, sem vergonha.",
        teach: [
          "Técnica 1 — narração: descreva em voz alta o que você está fazendo ('I'm making coffee, now I'm…').",
          "Técnica 2 — monólogo: fale 2 minutos sobre o seu dia, sem parar pra corrigir.",
          "Técnica 3 — pensar em inglês: troque o diálogo interno de tarefas simples pro inglês.",
          "Regra: foco em FLUIR, não em acertar. Errar falando é progresso.",
        ],
        task: "Faça 2 minutos de monólogo em voz alta sobre o seu dia. Sem pausar pra corrigir.",
        closing: "Falar sozinho parece estranho — e é o atalho mais rápido pra destravar a língua. Comece hoje.",
      },
      {
        id: "m5l3",
        title: "Sua primeira gravação de áudio",
        level: "Todos",
        duration: "7–9 min",
        hook: "A ferramenta mais poderosa pra evoluir a fala é o seu próprio celular. Hoje você grava seu primeiro áudio em inglês.",
        teach: [
          "Explique o poder de se gravar: você ouve seus erros, acompanha a evolução e cria coragem.",
          "Dê o roteiro do 1º áudio: apresente-se, fale sua meta de inglês e o que você ama fazer (60 segundos).",
          "Ensine a comparar: grave hoje e de novo em 30 dias pra ver o progresso.",
          "Incentive postar na comunidade pra receber apoio (não correção dura).",
        ],
        task: "Grave 60 segundos se apresentando em inglês e poste na thread de áudios da comunidade.",
        closing: "Seu primeiro áudio vai ser imperfeito — e é exatamente por isso que ele é tão valioso. Grave.",
      },
      {
        id: "m5l4",
        title: "Vencer o medo de errar (o filtro afetivo)",
        level: "Todos",
        duration: "9–11 min",
        hook: "O maior inimigo do seu inglês não é a gramática. É o medo de passar vergonha. Vamos desarmar isso de vez.",
        teach: [
          "Explique o filtro afetivo: medo e ansiedade bloqueiam literalmente a aquisição e a fala.",
          "Reframe do erro: cada erro é informação, não fracasso. Nativos erram a vida toda.",
          "Mostre que a comunidade é um ambiente seguro: a regra é apoio, não correção humilhante.",
          "Dê a técnica da exposição gradual: áudio → conversa com 1 parceiro → grupo pequeno → maior.",
        ],
        task: "Compartilhe na comunidade o erro mais 'vergonhoso' que você já cometeu (ou teme cometer) em inglês. Vamos rir juntos e seguir.",
        closing: "Quem tem medo de errar nunca fala. Quem aceita errar, fala — e fica fluente. Escolha errar.",
      },
    ],
  },
  {
    code: "M6",
    title: "Parceiro de Intercâmbio",
    goal: "Conseguir um parceiro real e manter a rotina de troca. Vale mais que tutor de IA.",
    lessons: [
      {
        id: "m6l1",
        title: "Por que parceiro humano real > tutor de voz com IA",
        level: "Todos",
        duration: "7–9 min",
        hook: "Todo mundo está empolgado com tutor de IA. Eu vou te mostrar por que um parceiro humano de verdade vence ele de longe.",
        teach: [
          "Motivo 1 — engajamento: conversar com gente real é divertido; com IA enjoa rápido.",
          "Motivo 2 — stakes reais: a vontade de ser entendido por uma pessoa te força a se esforçar de verdade.",
          "Motivo 3 — cultura e gírias: humanos trazem contexto, humor e expressões que IA não dá.",
          "Motivo 4 — accountability: um parceiro te espera; o app não cobra ninguém.",
          "Equilíbrio: IA pode ser apoio pontual, mas o output principal é com gente.",
        ],
        task: "Reflita e poste: você prefere conversar com pessoas ou com apps? Por quê? Isso define sua estratégia.",
        closing: "Idioma é conexão humana. Nenhuma IA substitui a emoção de ser entendido por outra pessoa.",
      },
      {
        id: "m6l2",
        title: "Onde encontrar parceiros de intercâmbio",
        level: "Todos",
        duration: "9–11 min",
        hook: "Vou te dar os lugares exatos onde encontrar gente disposta a praticar inglês com você — de graça.",
        teach: [
          "Apresente o diretório interno LatinusPro: outros membros buscando parceiro (comece por aqui).",
          "Liste apps de intercâmbio (Tandem, HelloTalk) e como usá-los com segurança.",
          "Mostre servidores de Discord de idiomas e comunidades de hobbies em inglês.",
          "Dica de ouro: pessoas aprendendo português querem trocar com brasileiros — você tem algo a oferecer.",
        ],
        task: "Crie seu anúncio no diretório de matchmaking da comunidade OU mande mensagem para 1 possível parceiro hoje.",
        closing: "Parceiro não cai do céu — você procura. Mas tem milhares querendo o que você oferece: o português.",
      },
      {
        id: "m6l3",
        title: "Como abordar e marcar a primeira conversa",
        level: "Todos",
        duration: "7–9 min",
        hook: "Achou um possível parceiro? Agora não trave na hora de chamar. Vou te dar as mensagens prontas.",
        teach: [
          "Dê o modelo de primeira mensagem: apresentação curta + proposta de troca (X min de inglês, X min de português).",
          "Combine o básico: idioma de cada metade, horário, frequência, plataforma (call de vídeo/áudio).",
          "Defina expectativa: combinar 30 minutos, 1x por semana, pra começar leve.",
          "Ensine a confirmar antes: mandar um lembrete no dia evita 'no-show'.",
        ],
        task: "Use o modelo de mensagem e marque sua primeira conversa de intercâmbio para esta semana.",
        closing: "A conversa que você adia pra 'quando estiver pronto' nunca acontece. Marque para esta semana.",
      },
      {
        id: "m6l4",
        title: "Roteiro pronto da primeira conversa (sem travar)",
        level: "Iniciante",
        duration: "8–10 min",
        hook: "Medo de ficar sem assunto na primeira conversa? Relaxa — eu vou te dar um roteiro pronto pra nunca travar.",
        teach: [
          "Dê perguntas de abertura prontas (de onde é, o que faz, hobbies).",
          "Ensine frases de socorro: 'How do you say… in English?', 'Can you repeat, please?', 'Sorry, my English is still improving.'",
          "Sugira temas seguros: viagens, filmes, comida, rotina, trabalho.",
          "Combine a estrutura: 15 min em inglês + 15 min em português, com 5 min de feedback gentil no fim.",
        ],
        task: "Salve as frases de socorro no celular e leve o roteiro para sua primeira conversa.",
        closing: "Você não precisa improvisar. Com um roteiro na mão, a primeira conversa deixa de ser terror e vira diversão.",
      },
      {
        id: "m6l5",
        title: "Montando uma rotina semanal de intercâmbio",
        level: "Todos",
        duration: "6–8 min",
        hook: "Uma conversa boa é ótima. Uma rotina de conversas é o que te deixa fluente. Vamos transformar isso em hábito.",
        teach: [
          "Defina a frequência mínima: 1x por semana fixo; ideal 2–3x.",
          "Ensine a agendar horário fixo (mesmo dia/hora) pra virar compromisso, não 'quando der'.",
          "Sugira manter 2–3 parceiros pra nunca depender de um só.",
          "Mostre como anotar palavras novas que surgem na conversa e levar pro sistema de vocabulário.",
        ],
        task: "Agende um horário fixo semanal de intercâmbio e adicione no seu calendário agora.",
        closing: "Fluência é frequência. Uma conversa por semana, toda semana, muda você em 90 dias.",
      },
    ],
  },
  {
    code: "M7",
    title: "Biblioteca de Fundamentos",
    goal: "Gramática sob demanda, self-paced. Iniciante segue em ordem; quem travou pega só as lacunas.",
    lessons: [
      {
        id: "m7l1",
        title: "Como usar esta biblioteca: pegue só o que te trava",
        level: "Todos",
        duration: "6–8 min",
        hook: "Atenção: esta NÃO é uma aula pra você decorar tudo. É uma biblioteca pra resolver problema. Deixa eu explicar como usar.",
        teach: [
          "Reforce a filosofia: gramática sob demanda — você consulta quando uma regra está te travando, não antes.",
          "Iniciante: percorra na ordem (Base → Essencial → Destravar).",
          "Intermediário: vá direto na lacuna que te incomoda. Não revise o que já domina.",
          "Lembre: a gramática são os 25%. Não deixe ela virar desculpa pra adiar a imersão e a fala.",
        ],
        task: "Identifique a regra de gramática que MAIS te confunde hoje e vá direto na aula dela.",
        closing: "Gramática é ferramenta, não muro. Pegue a peça que falta e volte logo pra falar.",
      },
      {
        id: "m7l2",
        title: "Base — to be, presente simples, artigos, perguntas",
        level: "Iniciante",
        duration: "12–15 min",
        hook: "Estas são as 4 estruturas que sustentam 80% das frases do dia a dia. Domine isso e você já consegue se comunicar.",
        teach: [
          "Verbo to be (am/is/are): apresentar-se, descrever, localizar.",
          "Presente simples: rotinas e fatos (I work, she likes), com atenção ao -s da 3ª pessoa.",
          "Artigos a/an/the: quando usar cada um, de forma simples e prática.",
          "Perguntas: como formar com do/does e com to be. Dê muitos exemplos falados.",
        ],
        task: "Escreva 5 frases sobre você usando to be e presente simples. Poste para feedback.",
        closing: "Com essas 4 estruturas você já monta conversas reais. O resto é detalhe que vem com o tempo.",
      },
      {
        id: "m7l3",
        title: "Essencial — passado simples, futuro, presente contínuo",
        level: "Iniciante",
        duration: "12–15 min",
        hook: "Agora que você fala no presente, vamos abrir o tempo: passado, futuro e o 'agora mesmo'. Aí sua comunicação explode.",
        teach: [
          "Passado simples: regulares (-ed) e os irregulares mais comuns (went, had, saw, did).",
          "Futuro: 'will' vs 'going to' — quando usar cada um, sem complicar.",
          "Presente contínuo (-ing): ações acontecendo agora (I'm studying).",
          "Foque nos verbos de altíssima frequência, não em listas enormes.",
        ],
        task: "Conte sua rotina de ontem (passado) e seus planos de amanhã (futuro) em 5 frases.",
        closing: "Presente, passado e futuro: com esses três tempos você já narra a vida inteira em inglês.",
      },
      {
        id: "m7l4",
        title: "Destravar — present perfect, condicionais, phrasal verbs, conectores",
        level: "Intermediário",
        duration: "14–16 min",
        hook: "Estas são as estruturas que separam o 'intermediário travado' do falante confiante. Vamos atacar as quatro.",
        teach: [
          "Present perfect: o tempo que mais confunde brasileiro (have done) — quando e por que usar.",
          "Condicionais (if): do zero ao terceiro, de forma prática e com exemplos reais.",
          "Phrasal verbs de alta frequência (get up, give up, look for…) — minerados do uso real.",
          "Conectores (however, although, so, because) pra soar natural e fluido.",
        ],
        task: "Escolha 1 das 4 estruturas e escreva 3 frases reais usando ela. Traga dúvidas para a call de Fundamentos.",
        closing: "Não é falta de gramática que te travou. É falta DESTAS estruturas específicas. Domine-as e destrave.",
      },
      {
        id: "m7l5",
        title: "Os erros fossilizados mais comuns do brasileiro",
        level: "Intermediário",
        duration: "12–14 min",
        hook: "Existem erros que o brasileiro repete há anos e nem percebe. Vou te mostrar os principais — e como corrigir de vez.",
        teach: [
          "'I have 30 years' → 'I am 30 years old'. (idade com to be)",
          "'I have a doubt' → 'I have a question'. (falso cognato)",
          "Confusões de pronúncia clássicas (th, vogais) e o sumiço do -s/-ed no fim das palavras.",
          "'People is' → 'People are', e outros erros de concordância recorrentes.",
          "Ensine a estratégia: escolher 1 erro fossilizado por vez e caçá-lo conscientemente até sumir.",
        ],
        task: "Identifique 1 erro fossilizado que você comete e se proponha a corrigi-lo por uma semana inteira.",
        closing: "Erro fossilizado não some com mais teoria — some com atenção consciente. Escolha um e mate-o esta semana.",
      },
    ],
  },
];

export const PATH: { step: string; title: string; note: string }[] = [
  { step: "00", title: "Comece Aqui — Primeiros 7 Dias", note: "Onboarding: vitória rápida e setup do sistema" },
  { step: "01", title: "M1 · Mentalidade & Quebra de Crenças", note: "Desbloqueio inicial (todos)" },
  { step: "02", title: "M2 · O Método LatinusPro", note: "O sistema + diagnóstico de ponto de partida" },
  { step: "03", title: "M3 · Sistema de Imersão", note: "Biblioteca de conteúdo por nível dentro do módulo" },
  { step: "04", title: "M4 · Sistema de Vocabulário", note: "Repetição espaçada + tracker de progresso" },
  { step: "05", title: "M5 · Destravar a Fala", note: "Output — onde o intermediário empaca" },
  { step: "06", title: "M6 · Parceiro de Intercâmbio", note: "Matchmaking interno" },
  { step: "07", title: "M7 · Biblioteca de Fundamentos", note: "Gramática self-paced: pega só o que precisa" },
  { step: "08", title: "Vault de Calls Gravadas", note: "Aulas e Conversation Clubs anteriores" },
];

export const ONBOARDING_LESSONS: Lesson[] = [
  {
    id: "onb0",
    title: "Boas-vindas",
    level: "Todos",
    tag: "Dia 0",
    duration: "5–7 min",
    hook: "Bem-vindo à LatinusPro! Antes de qualquer aula, os seus primeiros minutos aqui já decidem se você vai longe. Deixa eu te guiar.",
    teach: [
      "Dê as boas-vindas e relembre a promessa: a primeira conversa real em inglês em 90 dias.",
      "Faça um tour de 2 minutos do espaço: onde ficam as aulas (Classroom), o feed, o calendário das calls e o diretório de parceiros.",
      "Explique a regra de ouro da comunidade: ambiente de apoio — ninguém corrige de forma humilhante, todo mundo torce.",
      "Apresente o modelo do post de apresentação e mostre onde postar.",
    ],
    task: "Poste sua apresentação: nome, seu nível atual de inglês, por que você quer aprender e sua meta. Depois, reaja a 2 apresentações de outros membros.",
    closing: "Comunidade não é sobre conteúdo — é sobre gente. Se apresente e você já deu o passo mais importante.",
  },
  {
    id: "onb1",
    title: "A verdade sobre aprender inglês",
    level: "Todos",
    tag: "Dia 1",
    duration: "5 min + aula M1",
    hook: "Hoje sua missão é uma só: entender por que você ainda não fala inglês — e por que isso muda a partir de agora.",
    teach: [
      "Oriente o aluno a assistir a aula M1 · Aula 1 (A verdade sobre como adultos aprendem inglês).",
      "Reforce a mensagem central: o problema foi sempre o método, não você.",
      "Peça uma reflexão escrita curta para fixar a virada de chave.",
    ],
    task: "Assista a M1 · Aula 1 e poste em 1 frase: 'Sempre me ensinaram a ___, e por isso eu travei.'",
    closing: "Entender o problema é metade da solução. Amanhã a gente descobre exatamente por onde VOCÊ começa.",
  },
  {
    id: "onb2",
    title: "Diagnóstico de nível",
    level: "Todos",
    tag: "Dia 2",
    duration: "6–8 min",
    hook: "Aqui todo mundo segue o mesmo caminho. Hoje você só descobre por qual nível de conteúdo deve começar.",
    teach: [
      "Explique o teste de 2 minutos: assistir um conteúdo nativo (ex.: um podcast) e medir a compreensão.",
      "Dê o critério simples: entendeu a ideia geral → Intermediário; travou nas primeiras frases → Iniciante.",
      "Lembre que o nível só indica o material a consumir, não muda a jornada nem cria trilha separada.",
    ],
    task: "Faça o teste de 2 minutos, marque seu ponto de partida (Iniciante/Intermediário) no perfil e poste qual foi.",
    closing: "Ponto de partida definido. Agora a gente monta a sua máquina de aprender inglês.",
  },
  {
    id: "onb3",
    title: "Montar o sistema de imersão",
    level: "Todos",
    tag: "Dia 3",
    duration: "10–12 min",
    hook: "Hoje você monta a peça central do método: sua fonte diária de inglês que você AMA assistir.",
    teach: [
      "Oriente escolher 1 conteúdo de um tema que o aluno já ama em português.",
      "Mostre o passo a passo de instalar a extensão de legenda dupla (ex.: Language Reactor).",
      "Configure a legenda inglês + português e ensine como salvar palavras.",
      "Reforce: largar conteúdo chato sem culpa — tem que parecer lazer.",
    ],
    task: "Configure a legenda dupla em 1 vídeo, assista 5 minutos e poste um print do seu setup.",
    closing: "Pronto: você acabou de transformar o YouTube na sua escola de inglês particular e gratuita.",
  },
  {
    id: "onb4",
    title: "Montar o tracker de vocabulário",
    level: "Todos",
    tag: "Dia 4",
    duration: "10–12 min",
    hook: "Vamos criar o seu placar de progresso — o sistema que faz o vocabulário crescer e te dá aquela dopamina boa.",
    teach: [
      "Ajude a escolher a ferramenta: Language Reactor, Anki ou a planilha LatinusPro.",
      "Crie juntos os 5 primeiros flashcards, sempre com a palavra dentro de uma frase real.",
      "Explique a meta de 7 palavras novas por dia e por que menos é mais.",
    ],
    task: "Configure sua ferramenta e crie seus 5 primeiros flashcards. Poste qual ferramenta você escolheu.",
    closing: "Agora cada palavra nova vira ponto no placar. É assim que estudar deixa de ser obrigação e vira jogo.",
  },
  {
    id: "onb5",
    title: "Primeira imersão de 20 minutos",
    level: "Todos",
    tag: "Dia 5",
    duration: "5 min + 20 min de prática",
    hook: "Chega de teoria. Hoje você faz sua primeira sessão de imersão de verdade — e registra ela.",
    teach: [
      "Oriente fazer 20 minutos do conteúdo escolhido com legenda dupla.",
      "Minerar 5–8 palavras novas para o tracker durante a sessão.",
      "Registrar no log de imersão da comunidade (isso alimenta o streak e a gamificação).",
    ],
    task: "Faça 20 min de imersão, minere 8 palavras e poste seu primeiro log: 'Assisti X por 20 min, minerei 8 palavras.'",
    closing: "Esse é o hábito que muda tudo. Você não está 'estudando' inglês — está vivendo nele, 20 minutos por dia.",
  },
  {
    id: "onb6",
    title: "Primeira vitória pública",
    level: "Todos",
    tag: "Dia 6",
    duration: "5–7 min",
    hook: "A motivação não vem antes da ação — ela vem DEPOIS, quando você é celebrado. Hoje você posta sua primeira vitória.",
    teach: [
      "Explique o poder de compartilhar progresso: gatilho de recompensa + sensação de pertencimento.",
      "Dê exemplos de vitórias pequenas: entendeu uma frase sem legenda, completou o streak, gravou um áudio.",
      "Incentive o hábito de reagir e celebrar as vitórias dos outros membros.",
    ],
    task: "Poste sua primeira vitória na thread de 'Wins', por menor que pareça. E celebre a vitória de 2 colegas.",
    closing: "Progresso compartilhado é progresso multiplicado. Aqui, suas vitórias nunca passam despercebidas.",
  },
  {
    id: "onb7",
    title: "Meta de 90 dias + parceiro",
    level: "Todos",
    tag: "Dia 7",
    duration: "8–10 min",
    hook: "Última etapa do onboarding: cravar o seu destino. Hoje você define a meta de 90 dias e entra na fila de parceiros.",
    teach: [
      "Defina a meta padrão da comunidade: primeira conversa real de 10 minutos em 90 dias.",
      "Torne mensurável: vocabulário (ex.: +500 palavras), minutos de imersão por dia, nº de conversas.",
      "Mostre como entrar no diretório de matchmaking e criar o anúncio de parceiro.",
    ],
    task: "Escreva sua meta de 90 dias no perfil e crie seu anúncio no diretório de parceiros de intercâmbio.",
    closing: "Sistema montado, hábito iniciado, meta cravada. Bem-vindo de verdade — agora é girar a roda todo dia.",
  },
];

export const BELIEF_LESSONS: Lesson[] = [
  {
    id: "bel1",
    title: "Preciso morar fora para aprender",
    level: "Todos",
    tag: "Mito 1",
    duration: "10–12 min",
    hook: "Essa é a desculpa número 1 que eu ouço. E é exatamente ela que mantém gente travada por décadas. Vamos destruí-la.",
    teach: [
      "Apresente o mito e reconheça por que ele PARECE verdade (faz sentido na cabeça das pessoas).",
      "Vire a chave: o que ensina um idioma é input + output + motivação — não geografia.",
      "Mostre o paradoxo: morar fora SEM método não funciona; método SEM morar fora funciona muito bem.",
      "Explique o que realmente importa: exposição com sentido, uso real e baixo medo de errar.",
    ],
    example: "Dois imigrantes nos EUA: um vive há 10 anos e mal fala inglês (vive numa bolha, só fala português); o outro chegou já falando, porque estudou com método antes de viajar. Mesmo país, resultados opostos. A diferença nunca foi o lugar.",
    task: "Monte hoje 30 minutos de imersão na sua própria casa. Prove pra si mesmo que o país não importa.",
    closing: "Você não precisa de passaporte pra aprender inglês. Precisa de input, uso e coragem — e tudo isso cabe na sua sala.",
  },
  {
    id: "bel2",
    title: "Sou velho demais / não tenho dom",
    level: "Todos",
    tag: "Mito 2",
    duration: "8–10 min",
    hook: "Quantas vezes você disse 'não tenho dom pra idiomas'? Hoje eu provo que dom não existe — método existe.",
    teach: [
      "Derrube o mito do 'dom': não existe gene de idioma; existe estratégia e exposição.",
      "Mostre as vantagens do adulto: foco, disciplina e capacidade de reconhecer padrões.",
      "O que a criança tem a mais é tempo de exposição e ausência de medo — e os dois dá pra copiar.",
      "Reframe: 'não tenho dom' na verdade significa 'nunca usei o método certo'.",
    ],
    task: "Escolha 1 conteúdo que você ama e comece por ele hoje. Sua idade não vai te atrapalhar nem um pouco.",
    closing: "Dom é desculpa. Método é solução. E o método não pergunta a sua idade.",
  },
  {
    id: "bel3",
    title: "Preciso de gramática perfeita antes de falar",
    level: "Todos",
    tag: "Mito 3",
    duration: "8–10 min",
    hook: "Esse mito é traiçoeiro porque parece responsável. Mas é justamente ele que te impede de falar pra sempre.",
    teach: [
      "Mostre que fluência vem do uso, não do acúmulo de regras.",
      "Lembre: nativos aprenderam a FALAR muito antes de saber qualquer gramática.",
      "Esperar a 'gramática perfeita' é perseguir um alvo que nunca chega — autossabotagem disfarçada de cuidado.",
      "Posicione a gramática como os 25%, que vêm sob demanda, depois que você já está usando a língua.",
    ],
    task: "Grave 1 áudio de 60 segundos falando de você. Com erros. Especialmente com erros.",
    closing: "Você não vai falar quando a gramática estiver perfeita. A gramática fica boa porque você começou a falar.",
  },
  {
    id: "bel4",
    title: "Vou passar vergonha se errar",
    level: "Todos",
    tag: "Mito 4",
    duration: "9–11 min",
    hook: "Esse é o mito mais poderoso de todos, porque é emocional. E é o que mais trava a sua boca. Vamos desarmá-lo.",
    teach: [
      "Explique o filtro afetivo: medo e ansiedade bloqueiam literalmente a fala e a aquisição.",
      "Faça o reframe do erro: errar é dado, é como o cérebro calibra. Nativos erram a vida inteira.",
      "Mostre que o julgamento que você teme quase nunca existe — as pessoas costumam torcer por você.",
      "Posicione a comunidade como ambiente seguro de propósito: apoio, nunca correção humilhante.",
    ],
    task: "Poste na comunidade o erro mais 'vergonhoso' que você teme cometer em inglês. Vamos rir junto e seguir em frente.",
    closing: "Quem tem medo de errar, cala. Quem aceita errar, fala. A vergonha é o preço da fluência — e é um preço barato.",
  },
  {
    id: "bel5",
    title: "Não tenho tempo",
    level: "Todos",
    tag: "Mito 5",
    duration: "7–9 min",
    hook: "'Não tenho tempo' é meia verdade. Você TEM tempo — só está gastando ele todo em português. Deixa eu te mostrar.",
    teach: [
      "Mostre que imersão SUBSTITUI consumo que você já faz; ela não soma horas novas.",
      "Faça a conta de padaria: quantos minutos de YouTube, podcast e série você já consome por dia?",
      "Proponha trocar o idioma de PARTE desse tempo — começando com 15 minutos.",
      "Mostre o efeito composto: 20 min/dia = mais de 120 horas de inglês por ano.",
    ],
    task: "Hoje, troque 1 vídeo em português que você ia ver por 1 em inglês com legenda. Mesmo tempo, novo idioma.",
    closing: "Você não precisa de mais tempo. Precisa trocar o idioma do tempo que já tem — e isso é de graça.",
  },
  {
    id: "bel6",
    title: "Um app de idioma é suficiente",
    level: "Todos",
    tag: "Mito 6",
    duration: "8–10 min",
    hook: "Você baixou o app, fez 100 dias de ofensiva… e ainda não fala. Tem um motivo — e ele não é culpa sua.",
    teach: [
      "Reconheça o valor: apps são ótimos para criar hábito e gamificação.",
      "Mostre o limite: dão pouco input real e quase nenhum output com humanos.",
      "Aprender frases isoladas não é o mesmo que entender e conversar de verdade.",
      "Reposicione: input real (conteúdo que você ama) + fala com gente são a base; o app é só acessório.",
    ],
    task: "Defina seu input real (vídeo/áudio) como atividade principal hoje. Se quiser, use o app só como complemento de 5 min.",
    closing: "App nenhum te faz falar. Conteúdo real e gente real, sim. Use o app como tempero — nunca como prato principal.",
  },
];
export const TABS = [
  { id: "overview", label: "Visão Geral" },
  { id: "onboarding", label: "Primeiros 7 Dias" },
  { id: "journey", label: "A Jornada (Currículo)" },
  { id: "beliefs", label: "Quebra de Crenças" },
  { id: "calls", label: "Calls & Rituais" },
] as const;
